---
# This is a role for setting up the server.

- name: Install packages
  apt:
    pkg:
     - apache2
     - libapache2-mod-php
     - mysql-server
     - mysql-client
     - python3
    update_cache: yes

- name: Create alias for client
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.30.5 client'

- name: Create super_secret directory
  file:
    path: /var/www/html/super_secret
    state: directory

- name: Create super_secret phpinfor file
  copy:
    dest: /var/www/html/super_secret/phpinfo.php
    src: phpinfo.php

- name: Create phpinfor file
  copy:
    dest: /var/www/html/phpinfo.php
    src: phpinfo.php

# Include Config mysql
- include_tasks: config_mysql.yml

...
